### ISSUE TITLE
Excludes

### ISSUE THREAD

**Issue by trinaryouroboros** [farbeiza/gdrsync.py#6]
This is more of a long-term feature request.

You may already know, rsync itself has a suite of handy excludes you can perform.

Was hoping, perhaps an array can be set up in gdrsync.py - such that, if "--exclude=" is present, append each exclude parameter to this new array and check for these excludes during run.

So, for example, if I wanted to exclude all "*.jpg", and the folder "./myfiles/junk", I might do something like this:

```./gdrsync.py -d -r -s -u -v /home/userhome/stuff/ /my.gdrsync/stuff/ --exclude="*.jpg" --exclude="myfiles/junk"```

...then, for each exclude, exarray.append(exclude) - and during sync operations, use an "if/then" chain or "case" to determine if the next object is in exarray, and skip the object if it is.

It might be even more powerful to implement some general regular expressions functionality, too.

Example excludes in rsync itself can be found here:

http://www.thegeekstuff.com/2011/01/rsync-exclude-files-and-folders/

**Comment by farbeiza** [comment]
Finally implemented using using regular expressions: --exclude='.*\.jpg
